import { Property } from '@/types/property';

export const mockProperties: Property[] = [
  {
    id: 'prop-001',
    title: 'Apartamento 3 quartos - Vila Madalena',
    description: 'Excelente apartamento no coração da Vila Madalena, 85m² com 3 quartos, 2 banheiros, sala ampla e cozinha planejada. Imóvel em bom estado de conservação, localizado em andar alto com vista privilegiada. Condomínio com portaria 24h, academia e piscina.',
    mainImage: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800',
    galleryImages: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
    ],
    address: 'Rua Girassol, 450, Apto 82',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '05433-000',
    latitude: -23.5604,
    longitude: -46.6933,
    marketValue: 680000,
    initialBid: 374000,
    discountPercentage: 45,
    auctionDate: '2026-03-25T10:00:00Z',
    auctionTime: '10:00',
    occupationStatus: 'VACANT',
    propertyType: 'APARTMENT',
    sourceBank: 'Caixa Econômica Federal',
    sourceAuctioneer: 'Zuk Leilões',
    registrationNumber: '123.456',
    legalIssues: ['Penhora judicial', 'IPTU em atraso (2 anos)'],
    areaTotal: 85,
    areaPrivate: 78,
    active: true,
    createdAt: '2026-02-01T00:00:00Z',
    updatedAt: '2026-02-15T00:00:00Z',
    auction: {
      id: 'auc-001',
      auctioneerName: 'Zuk Leilões',
      auctioneerWebsite: 'https://www.zuk.com.br',
      modalidade: '2º Leilão',
      auctionNumber: '2024/001',
    },
  },
  {
    id: 'prop-002',
    title: 'Casa 4 quartos com piscina - Alphaville',
    description: 'Magnífica casa em condomínio fechado de alto padrão em Alphaville. 320m² de área construída, 4 suítes, escritório, sala de jantar e estar integradas, cozinha gourmet, área de lazer com piscina e churrasqueira. Garagem para 4 carros.',
    mainImage: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800',
    galleryImages: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
    ],
    address: 'Alameda Madeiras, 1200',
    city: 'Barueri',
    state: 'SP',
    zipCode: '06474-000',
    latitude: -23.5015,
    longitude: -46.8481,
    marketValue: 2100000,
    initialBid: 1050000,
    discountPercentage: 50,
    auctionDate: '2026-04-10T14:00:00Z',
    auctionTime: '14:00',
    occupationStatus: 'OCCUPIED',
    propertyType: 'HOUSE',
    sourceBank: 'Itaú',
    sourceAuctioneer: 'Mega Leilões',
    registrationNumber: '98.765',
    legalIssues: ['Imóvel ocupado - possível ação de reintegração necessária'],
    areaTotal: 450,
    areaPrivate: 320,
    active: true,
    createdAt: '2026-01-15T00:00:00Z',
    updatedAt: '2026-02-20T00:00:00Z',
    auction: {
      id: 'auc-002',
      auctioneerName: 'Mega Leilões',
      auctioneerWebsite: 'https://www.megaleiloes.com.br',
      modalidade: '1º Leilão',
      auctionNumber: '2024/045',
    },
  },
  {
    id: 'prop-003',
    title: 'Terreno 500m² - Bairro Jardim América',
    description: 'Terreno plano com 500m² em bairro nobre, totalmente murado e com projeto aprovado para construção de sobrado. Excelente localização, próximo a escolas, comércio e transporte público. Documentação completa e sem ônus.',
    mainImage: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800',
    galleryImages: [],
    address: 'Rua das Acácias, 340',
    city: 'Curitiba',
    state: 'PR',
    zipCode: '80620-010',
    latitude: -25.4290,
    longitude: -49.2671,
    marketValue: 420000,
    initialBid: 210000,
    discountPercentage: 50,
    auctionDate: '2026-03-30T09:00:00Z',
    auctionTime: '09:00',
    occupationStatus: 'VACANT',
    propertyType: 'LAND',
    sourceBank: 'Banco do Brasil',
    sourceAuctioneer: 'Sodré Santoro',
    registrationNumber: '45.678',
    legalIssues: [],
    areaTotal: 500,
    active: true,
    createdAt: '2026-02-05T00:00:00Z',
    updatedAt: '2026-02-18T00:00:00Z',
    auction: {
      id: 'auc-003',
      auctioneerName: 'Sodré Santoro',
      auctioneerWebsite: 'https://www.sodresantoro.com.br',
      modalidade: '2º Leilão',
      auctionNumber: '2024/089',
    },
  },
  {
    id: 'prop-004',
    title: 'Apartamento 2 quartos - Beira Mar',
    description: 'Lindo apartamento com vista para o mar, 70m², 2 quartos sendo 1 suíte, sala com varanda gourmet e vista privilegiada para o oceano. Andar alto, condomínio com piscina, academia e área de festas.',
    mainImage: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800',
    galleryImages: [
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800',
    ],
    address: 'Av. Beira Mar Norte, 2000, Apto 1504',
    city: 'Florianópolis',
    state: 'SC',
    zipCode: '88015-000',
    latitude: -27.5954,
    longitude: -48.5480,
    marketValue: 750000,
    initialBid: 375000,
    discountPercentage: 50,
    auctionDate: '2026-04-05T10:00:00Z',
    auctionTime: '10:00',
    occupationStatus: 'VACANT',
    propertyType: 'APARTMENT',
    sourceBank: 'Bradesco',
    sourceAuctioneer: 'Lance Certo',
    registrationNumber: '67.890',
    legalIssues: ['Condomínio em atraso (6 meses)'],
    areaTotal: 70,
    areaPrivate: 65,
    active: true,
    createdAt: '2026-02-10T00:00:00Z',
    updatedAt: '2026-02-22T00:00:00Z',
    auction: {
      id: 'auc-004',
      auctioneerName: 'Lance Certo',
      auctioneerWebsite: 'https://www.lancecerto.com.br',
      modalidade: '1º Leilão',
      auctionNumber: '2024/102',
    },
  },
  {
    id: 'prop-005',
    title: 'Sala Comercial - Centro Empresarial',
    description: 'Sala comercial de 45m² em edifício corporativo de alto padrão no centro empresarial. Acabamento completo, ar-condicionado central, 2 vagas de garagem. Localização estratégica próxima a bancos, restaurantes e transporte.',
    mainImage: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800',
    galleryImages: [],
    address: 'Av. Presidente Vargas, 950, Sala 1210',
    city: 'Rio de Janeiro',
    state: 'RJ',
    zipCode: '20071-003',
    latitude: -22.9068,
    longitude: -43.1729,
    marketValue: 380000,
    initialBid: 190000,
    discountPercentage: 50,
    auctionDate: '2026-04-20T11:00:00Z',
    auctionTime: '11:00',
    occupationStatus: 'VACANT',
    propertyType: 'COMMERCIAL',
    sourceBank: 'Santander',
    sourceAuctioneer: 'Superbid',
    registrationNumber: '23.456',
    legalIssues: [],
    areaTotal: 45,
    areaPrivate: 45,
    active: true,
    createdAt: '2026-02-12T00:00:00Z',
    updatedAt: '2026-02-25T00:00:00Z',
    auction: {
      id: 'auc-005',
      auctioneerName: 'Superbid',
      auctioneerWebsite: 'https://www.superbid.net',
      modalidade: '2º Leilão',
      auctionNumber: '2024/156',
    },
  },
  {
    id: 'prop-006',
    title: 'Casa Popular 3 quartos - Parque Industrial',
    description: 'Casa popular com 90m², 3 quartos, 1 banheiro, sala, cozinha e área de serviço. Imóvel em bom estado geral, com quintal de 80m². Bairro residencial tranquilo com fácil acesso a transporte público.',
    mainImage: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800',
    galleryImages: [],
    address: 'Rua João Pessoa, 782',
    city: 'Campinas',
    state: 'SP',
    zipCode: '13034-040',
    latitude: -22.9099,
    longitude: -47.0626,
    marketValue: 280000,
    initialBid: 112000,
    discountPercentage: 60,
    auctionDate: '2026-03-28T09:30:00Z',
    auctionTime: '09:30',
    occupationStatus: 'OCCUPIED',
    propertyType: 'HOUSE',
    sourceBank: 'Caixa Econômica Federal',
    sourceAuctioneer: 'Zuk Leilões',
    registrationNumber: '12.345',
    legalIssues: ['Imóvel ocupado pelo devedor'],
    areaTotal: 170,
    areaPrivate: 90,
    active: true,
    createdAt: '2026-01-20T00:00:00Z',
    updatedAt: '2026-02-10T00:00:00Z',
    auction: {
      id: 'auc-006',
      auctioneerName: 'Zuk Leilões',
      auctioneerWebsite: 'https://www.zuk.com.br',
      modalidade: '2º Leilão',
      auctionNumber: '2024/178',
    },
  },
  {
    id: 'prop-007',
    title: 'Fazenda 50 hectares - Região Pecuária',
    description: 'Fazenda de 50 hectares com sede, 2 casas de funcionários, curral, piquetes formados e pastagem nativa. Boa infraestrutura, poço artesiano e energia elétrica. Excelente para pecuária ou agricultura.',
    mainImage: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800',
    galleryImages: [],
    address: 'Estrada Rural KM 15, Zona Rural',
    city: 'Uberlândia',
    state: 'MG',
    zipCode: '38400-000',
    latitude: -18.9186,
    longitude: -48.2772,
    marketValue: 1800000,
    initialBid: 900000,
    discountPercentage: 50,
    auctionDate: '2026-04-15T14:00:00Z',
    auctionTime: '14:00',
    occupationStatus: 'OCCUPIED',
    propertyType: 'RURAL',
    sourceBank: 'Banco do Brasil',
    sourceAuctioneer: 'Sodré Santoro',
    registrationNumber: '78.901',
    legalIssues: ['Arrendatários com contrato vigente'],
    areaTotal: 500000,
    active: true,
    createdAt: '2026-01-25T00:00:00Z',
    updatedAt: '2026-02-15T00:00:00Z',
    auction: {
      id: 'auc-007',
      auctioneerName: 'Sodré Santoro',
      auctioneerWebsite: 'https://www.sodresantoro.com.br',
      modalidade: '1º Leilão',
      auctionNumber: '2024/201',
    },
  },
  {
    id: 'prop-008',
    title: 'Cobertura Duplex - Miramar',
    description: 'Cobertura duplex com 180m² privativos, 4 suítes, sala de estar e jantar com pé-direito duplo, terraço com piscina privativa e churrasqueira. Acabamento de luxo, cozinha gourmet. 3 vagas de garagem.',
    mainImage: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800',
    galleryImages: [],
    address: 'Av. Sete de Setembro, 3000, Cobertura',
    city: 'Salvador',
    state: 'BA',
    zipCode: '40060-000',
    latitude: -12.9714,
    longitude: -38.5014,
    marketValue: 1500000,
    initialBid: 600000,
    discountPercentage: 60,
    auctionDate: '2026-04-25T10:00:00Z',
    auctionTime: '10:00',
    occupationStatus: 'VACANT',
    propertyType: 'APARTMENT',
    sourceBank: 'BTG Pactual',
    sourceAuctioneer: 'Mega Leilões',
    registrationNumber: '34.567',
    legalIssues: ['Penhora por dívida trabalhista'],
    areaTotal: 220,
    areaPrivate: 180,
    active: true,
    createdAt: '2026-02-01T00:00:00Z',
    updatedAt: '2026-02-20T00:00:00Z',
    auction: {
      id: 'auc-008',
      auctioneerName: 'Mega Leilões',
      auctioneerWebsite: 'https://www.megaleiloes.com.br',
      modalidade: '1º Leilão',
      auctionNumber: '2024/234',
    },
  },
  {
    id: 'prop-009',
    title: 'Apartamento 1 quarto - Pinheiros',
    description: 'Studio moderno de 38m² no bairro de Pinheiros, reformado com móveis planejados, ar-condicionado e 1 vaga de garagem. Ideal para investimento em aluguel, excelente rendimento mensal estimado.',
    mainImage: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    galleryImages: [],
    address: 'Rua dos Pinheiros, 1500, Apto 45',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '05422-010',
    latitude: -23.5681,
    longitude: -46.6850,
    marketValue: 320000,
    initialBid: 160000,
    discountPercentage: 50,
    auctionDate: '2026-05-05T10:00:00Z',
    auctionTime: '10:00',
    occupationStatus: 'VACANT',
    propertyType: 'APARTMENT',
    sourceBank: 'Caixa Econômica Federal',
    sourceAuctioneer: 'Zuk Leilões',
    registrationNumber: '56.789',
    legalIssues: [],
    areaTotal: 38,
    areaPrivate: 35,
    active: true,
    createdAt: '2026-02-08T00:00:00Z',
    updatedAt: '2026-02-22T00:00:00Z',
    auction: {
      id: 'auc-009',
      auctioneerName: 'Zuk Leilões',
      auctioneerWebsite: 'https://www.zuk.com.br',
      modalidade: '2º Leilão',
      auctionNumber: '2024/267',
    },
  },
  {
    id: 'prop-010',
    title: 'Galpão Industrial 1000m² - Zona Industrial',
    description: 'Galpão industrial com 1000m² de área construída, pé-direito de 8m, 3 portões de acesso, escritório administrativo, refeitório e vestiários. Piso de concreto reforçado, área de manobra externa. Documentação em dia.',
    mainImage: 'https://images.unsplash.com/photo-1565426873118-a17ed65d74b9?w=800',
    galleryImages: [],
    address: 'Rua Industrial, 500, Galpão 3',
    city: 'Porto Alegre',
    state: 'RS',
    zipCode: '91240-000',
    latitude: -30.0346,
    longitude: -51.2177,
    marketValue: 2500000,
    initialBid: 1250000,
    discountPercentage: 50,
    auctionDate: '2026-05-10T14:00:00Z',
    auctionTime: '14:00',
    occupationStatus: 'VACANT',
    propertyType: 'COMMERCIAL',
    sourceBank: 'Votorantim',
    sourceAuctioneer: 'Superbid',
    registrationNumber: '89.012',
    legalIssues: ['Passivo ambiental a verificar'],
    areaTotal: 2000,
    areaPrivate: 1000,
    active: true,
    createdAt: '2026-02-14T00:00:00Z',
    updatedAt: '2026-02-28T00:00:00Z',
    auction: {
      id: 'auc-010',
      auctioneerName: 'Superbid',
      auctioneerWebsite: 'https://www.superbid.net',
      modalidade: '1º Leilão',
      auctionNumber: '2024/298',
    },
  },
  {
    id: 'prop-011',
    title: 'Casa Geminada 2 quartos - Vila Operária',
    description: 'Casa geminada com 65m², 2 quartos, sala, cozinha e área de serviço. Imóvel em bom estado, com garagem coberta para 1 carro. Bairro residencial com comércio local e fácil acesso à linha de ônibus.',
    mainImage: 'https://images.unsplash.com/photo-1558036117-15d82a90b9b1?w=800',
    galleryImages: [],
    address: 'Rua Tiradentes, 234',
    city: 'Belo Horizonte',
    state: 'MG',
    zipCode: '30110-040',
    latitude: -19.9191,
    longitude: -43.9386,
    marketValue: 220000,
    initialBid: 99000,
    discountPercentage: 55,
    auctionDate: '2026-03-22T09:00:00Z',
    auctionTime: '09:00',
    occupationStatus: 'UNKNOWN',
    propertyType: 'HOUSE',
    sourceBank: 'Caixa Econômica Federal',
    sourceAuctioneer: 'Lance Certo',
    registrationNumber: '11.111',
    legalIssues: ['Dívida de IPTU (3 anos)'],
    areaTotal: 120,
    areaPrivate: 65,
    active: true,
    createdAt: '2026-01-18T00:00:00Z',
    updatedAt: '2026-02-05T00:00:00Z',
    auction: {
      id: 'auc-011',
      auctioneerName: 'Lance Certo',
      auctioneerWebsite: 'https://www.lancecerto.com.br',
      modalidade: '2º Leilão',
      auctionNumber: '2024/312',
    },
  },
  {
    id: 'prop-013',
    title: 'Apartamento 2 quartos - Boa Vista',
    description: 'Apartamento 2 quartos em bom estado, 58m², sala, cozinha e banheiro. Localizado em bairro residencial tranquilo. Oportunidade rara com desconto excepcional em 2ª praça.',
    mainImage: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
    galleryImages: [],
    address: 'Rua das Flores, 1200, Apto 301',
    city: 'Recife',
    state: 'PE',
    zipCode: '52041-020',
    latitude: -8.0476,
    longitude: -34.8770,
    marketValue: 320000,
    initialBid: 48000,
    discountPercentage: 85,
    auctionDate: '2026-04-18T10:00:00Z',
    auctionTime: '10:00',
    occupationStatus: 'VACANT',
    propertyType: 'APARTMENT',
    sourceBank: 'Caixa Econômica Federal',
    sourceAuctioneer: 'Zuk Leilões',
    registrationNumber: '22.333',
    legalIssues: ['Penhora judicial', 'IPTU em atraso (4 anos)'],
    areaTotal: 58,
    areaPrivate: 52,
    active: true,
    createdAt: '2026-03-01T00:00:00Z',
    updatedAt: '2026-03-15T00:00:00Z',
    auction: {
      id: 'auc-013',
      auctioneerName: 'Zuk Leilões',
      auctioneerWebsite: 'https://www.zuk.com.br',
      modalidade: '2º Leilão',
      auctionNumber: '2024/399',
    },
  },
  {
    id: 'prop-014',
    title: 'Casa 3 quartos - Conjunto Habitacional',
    description: 'Casa popular de 75m² com 3 quartos, sala, cozinha e quintal. Imóvel com dívidas acumuladas — oportunidade de investimento com desconto excepcional em 2ª praça.',
    mainImage: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800',
    galleryImages: [],
    address: 'Rua Coronel Pedro, 456',
    city: 'Fortaleza',
    state: 'CE',
    zipCode: '60861-070',
    latitude: -3.7172,
    longitude: -38.5434,
    marketValue: 450000,
    initialBid: 54000,
    discountPercentage: 88,
    auctionDate: '2026-04-22T09:00:00Z',
    auctionTime: '09:00',
    occupationStatus: 'VACANT',
    propertyType: 'HOUSE',
    sourceBank: 'Banco do Brasil',
    sourceAuctioneer: 'Lance Certo',
    registrationNumber: '44.555',
    legalIssues: ['IPTU em atraso (5 anos)', 'Penhora por dívida condominial'],
    areaTotal: 120,
    areaPrivate: 75,
    active: true,
    createdAt: '2026-03-05T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
    auction: {
      id: 'auc-014',
      auctioneerName: 'Lance Certo',
      auctioneerWebsite: 'https://www.lancecerto.com.br',
      modalidade: '2º Leilão',
      auctionNumber: '2024/412',
    },
  },
  {
    id: 'prop-015',
    title: 'Apartamento Quitinete - Pituba',
    description: 'Quitinete de 32m² completamente reformada, ar-condicionado incluso, 1 vaga de garagem. Excelente para investimento em aluguel — alta demanda na região.',
    mainImage: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
    galleryImages: [],
    address: 'Av. Paulo VI, 2800, Apto 1101',
    city: 'Salvador',
    state: 'BA',
    zipCode: '41810-001',
    latitude: -12.9795,
    longitude: -38.4616,
    marketValue: 280000,
    initialBid: 50400,
    discountPercentage: 82,
    auctionDate: '2026-04-28T10:00:00Z',
    auctionTime: '10:00',
    occupationStatus: 'VACANT',
    propertyType: 'APARTMENT',
    sourceBank: 'Caixa Econômica Federal',
    sourceAuctioneer: 'Mega Leilões',
    registrationNumber: '66.777',
    legalIssues: ['Condomínio em atraso (3 anos)'],
    areaTotal: 32,
    areaPrivate: 30,
    active: true,
    createdAt: '2026-03-10T00:00:00Z',
    updatedAt: '2026-03-20T00:00:00Z',
    auction: {
      id: 'auc-015',
      auctioneerName: 'Mega Leilões',
      auctioneerWebsite: 'https://www.megaleiloes.com.br',
      modalidade: '2º Leilão',
      auctionNumber: '2024/425',
    },
  },
  {
    id: 'prop-012',
    title: 'Penthouse com Vista Panorâmica - Boa Viagem',
    description: 'Penthouse de alto padrão com 250m², 5 quartos sendo 3 suítes master, vista panorâmica 360° do mar e cidade, terraço privativo de 80m², cozinha gourmet completa e adega climatizada.',
    mainImage: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
    galleryImages: [],
    address: 'Av. Boa Viagem, 4000, Cobertura',
    city: 'Recife',
    state: 'PE',
    zipCode: '51030-000',
    latitude: -8.1181,
    longitude: -34.9001,
    marketValue: 3200000,
    initialBid: 1280000,
    discountPercentage: 60,
    auctionDate: '2026-05-15T10:00:00Z',
    auctionTime: '10:00',
    occupationStatus: 'VACANT',
    propertyType: 'APARTMENT',
    sourceBank: 'BTG Pactual',
    sourceAuctioneer: 'Mega Leilões',
    registrationNumber: '99.123',
    legalIssues: [],
    areaTotal: 330,
    areaPrivate: 250,
    active: true,
    createdAt: '2026-02-20T00:00:00Z',
    updatedAt: '2026-03-01T00:00:00Z',
    auction: {
      id: 'auc-012',
      auctioneerName: 'Mega Leilões',
      auctioneerWebsite: 'https://www.megaleiloes.com.br',
      modalidade: '1º Leilão',
      auctionNumber: '2024/345',
    },
  },
];

export function filterProperties(properties: Property[], filters: {
  state?: string;
  propertyType?: string;
  minValue?: number;
  maxValue?: number;
  sourceBank?: string;
  sourceAuctioneer?: string;
  occupationStatus?: string;
  modalidade?: string;
  paymentMethod?: string;
  campaignId?: string;
  search?: string;
  searchAddress?: boolean;
  sortBy?: string;
}): Property[] {
  // Remove acentos para busca insensível a acentuação ("Sao Paulo" == "São Paulo")
  const norm = (s: string) =>
    s.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase();

  // Pre-compile word-boundary regex (normalizada) uma vez para todos os campos
  let wordRe: RegExp | null = null;
  let normSearch = '';
  if (filters.search?.trim()) {
    normSearch = norm(filters.search.trim());
    const escaped = normSearch.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    wordRe = new RegExp(`(^|[\\s,/\\-])${escaped}([\\s,/\\-]|$)`, 'i');
  }

  const result = properties.filter((p) => {
    if (filters.state && p.state !== filters.state) return false;
    if (filters.propertyType && p.propertyType !== filters.propertyType) return false;
    if (filters.minValue && p.initialBid < filters.minValue) return false;
    if (filters.maxValue && p.initialBid > filters.maxValue) return false;
    if (filters.sourceBank && p.sourceBank !== filters.sourceBank) return false;
    if (filters.sourceAuctioneer && p.sourceAuctioneer !== filters.sourceAuctioneer) return false;
    if (filters.occupationStatus && p.occupationStatus !== filters.occupationStatus) return false;
    if (filters.modalidade && p.auction?.modalidade !== filters.modalidade) return false;
    if (filters.paymentMethod && !p.paymentMethods?.some((m) => m.toLowerCase().includes(filters.paymentMethod!.toLowerCase()))) return false;
    if (filters.campaignId && p.campaignId !== filters.campaignId) return false;
    if (wordRe) {
      if (
        !wordRe.test(norm(p.city)) &&
        !wordRe.test(norm(p.title)) &&
        !wordRe.test(norm(p.state)) &&
        !(filters.searchAddress && norm(p.address).includes(normSearch))
      ) return false;
    }
    return true;
  });

  switch (filters.sortBy) {
    case 'price_asc':    return [...result].sort((a, b) => a.initialBid - b.initialBid);
    case 'price_desc':   return [...result].sort((a, b) => b.initialBid - a.initialBid);
    case 'discount_desc':return [...result].sort((a, b) => b.discountPercentage - a.discountPercentage);
    case 'discount_asc': return [...result].sort((a, b) => a.discountPercentage - b.discountPercentage);
    case 'value_desc':   return [...result].sort((a, b) => b.marketValue - a.marketValue);
    case 'value_asc':    return [...result].sort((a, b) => a.marketValue - b.marketValue);
    default:             return result;
  }
}
